### ISSUE TITLE
[BUG] ViperFx partially does not work

### ISSUE THREAD

**Issue by SavvaGrigoryan** [Lethany/BeyondROM_Hub#2] opened 2021-11-28 19:46 UTC
I have been observing this problem for a long time. I was sent here to write this issue. 
Processing works in almost any application except games. Legacy mode is enabled.

![Screenshot_20211128-223601_True Skate](https://user-images.githubusercontent.com/25353752/143783358-9488ea9f-380d-4c93-8a7a-18cafe7c828e.jpg)

Smartphone
 - Device: [Galaxy S10]
 - Model: [G973F]
 
I myself do not know what the problem is. ROM or ViperFx. I was told to write here. If something is known about this problem, then let me know. I love your ROM♥️

**Comment by Lethany** [comment] 2021-11-28 19:48
@SavvaGrigoryan Do you have any other conflicting audio modules installed, and do you use the Audio Modification Library module?

**Comment by SavvaGrigoryan** [comment] 2021-11-28 19:56
@Lethany only built-in dolby atmos. AML module is installed.

**Comment by Lethany** [comment] 2021-11-28 19:58
@SavvaGrigoryan Have you tried reinstalling V4A, and what version of Beyond are you using?

**Comment by SavvaGrigoryan** [comment] 2021-11-28 20:03
@Lethany I have tried all versions of viperfix. I tried absolutely everything and even made it systemic. BR 8.8

**Comment by Lethany** [comment] 2021-11-28 20:09
@SavvaGrigoryan Just to clarify, V4A works for playing normal music like in Spotify?

**Comment by Lethany** [comment] 2021-11-28 20:13
@Lethany Also, can you provide a logcat using the log-all from the LoggingKit, and confirm this problem happens with both phone speakers and when using headphones?

**Comment by SavvaGrigoryan** [comment] 2021-11-28 20:20
@Lethany Spotify successfully processes. Processing is missing only in games on the speaker and headphones. But, bluetooth headphones have processing in games.

**Comment by Lethany** [comment] 2021-11-28 20:21
@SavvaGrigoryan Is this happening in all games or just a specific game?

**Comment by SavvaGrigoryan** [comment] 2021-11-28 20:24
@Lethany absolutely in all

**Comment by Lethany** [comment] 2021-11-28 20:25
@SavvaGrigoryan Does this also persist after a clean install of the rom?

**Comment by SavvaGrigoryan** [comment] 2021-11-28 20:27
@Lethany Yes, I have tried many times to put Viper on pure ROM

**Comment by Lethany** [comment] 2021-11-28 20:33
@SavvaGrigoryan To confirm, you are using the very latest version of V4A?

**Comment by SavvaGrigoryan** [comment] 2021-11-28 20:35
@Lethany Yes. 2.7.2.1

**Comment by Lethany** [comment] 2021-11-28 20:36
@SavvaGrigoryan Can you open a game and provide a logcat so we can try figure out this error?

**Comment by SavvaGrigoryan** [comment] 2021-11-28 20:38
@Lethany I will try

**Comment by SavvaGrigoryan** [comment] 2021-11-28 21:09
[log_All.log](https://github.com/Lethany/BeyondROM_Hub/files/7614373/log_All.log)

@Lethany

**Comment by Lethany** [comment] 2021-11-28 21:14
@SavvaGrigoryan Log is showing some permission errors, can you make sure the V4A has all the correct permissions granted?

**Comment by SavvaGrigoryan** [comment] 2021-11-28 21:18
@Lethany what permissions does he need?

**Comment by Lethany** [comment] 2021-11-28 21:19
@SavvaGrigoryan Check the permissions for the V4A app in Settings, and make sure all are granted.

**Comment by Lethany** [comment] 2021-11-28 21:21
@SavvaGrigoryan Asides from this issue, it also appears that Customisation Service is crashing on your phone too, can you clear the data of that app in Settings?

11-28 23:51:52.380  9086  9086 E AndroidRuntime: FATAL EXCEPTION: main
11-28 23:51:52.380  9086  9086 E AndroidRuntime: Process: com.samsung.android.rubin.app, PID: 9086
11-28 23:51:52.380  9086  9086 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.samsung.android.rubin.app.RubinApplication: com.samsung.context.sdk.samsunganalytics.AnalyticsException: Failed to get DMA version

**Comment by SavvaGrigoryan** [comment] 2021-11-28 21:21
@Lethany it doesn't require any permission. There is no item with permissions in the settings.

**Comment by Lethany** [comment] 2021-11-28 21:25
@SavvaGrigoryan Can you fully uninstall the V4A Module, reboot your phone then reinstall the module, reboot and try playing v4a on a game again and let me know of the outcome?

**Comment by SavvaGrigoryan** [comment] 2021-11-28 21:27
@Lethany OK. I'm going to try now

**Comment by Lethany** [comment] 2021-11-28 21:43
@SavvaGrigoryan Alright.

**Comment by SavvaGrigoryan** [comment] 2021-11-28 21:45
@Lethany reinstalled completely. Erased application data. The problem is not solved =(

**Comment by Lethany** [comment] 2021-11-28 21:46
@SavvaGrigoryan I have another user test this problem to see if it just your device.

**Comment by SavvaGrigoryan** [comment] 2021-11-28 21:51
@Lethany Ok. Is anything required of me now? Or do I have to wait for now?

**Comment by Lethany** [comment] 2021-11-28 21:51
@SavvaGrigoryan Have you tried removing the Audio Modification Library?

**Comment by SavvaGrigoryan** [comment] 2021-11-28 21:52
@Lethany now, after installing Viper - no

**Comment by Lethany** [comment] 2021-11-28 21:53
@SavvaGrigoryan Can you try with it removed?

**Comment by SavvaGrigoryan** [comment] 2021-11-28 21:58
@Lethany to clean Viperfx and remove AML?

**Comment by Lethany** [comment] 2021-11-28 21:59
@SavvaGrigoryan Yes, remove every module and reboot then add v4a but not AML.

**Comment by SavvaGrigoryan** [comment] 2021-11-28 22:09
@Lethany no changes

**Comment by Lethany** [comment] 2021-11-28 22:09
@SavvaGrigoryan This problem may be linked to V4A itself, but I will get another user to test your issue to see.

**Comment by SavvaGrigoryan** [comment] 2021-11-28 22:13
@Lethany I contacted the administrator in the telegram group VIPER. Here is his answer: Depends on game if they stream his audio session id. Has nothing to do with firmware (maybe ingame engine(?)) or is device specific :/

**Comment by Lethany** [comment] 2021-11-28 22:33
@SavvaGrigoryan Ok so the issue is not the ROM and the issue is on V4A's side.

**Comment by SavvaGrigoryan** [comment] 2021-11-28 22:42
@Lethany I already thought that something fell off for me🤣
Then we have to wait for a fix from Viper?

**Comment by Lethany** [comment] 2021-11-28 22:43
@SavvaGrigoryan Possibly yes.

**Comment by SavvaGrigoryan** [comment] 2021-11-28 22:45
@Lethany then thanks anyway for the help. At least they understood the reason.

**Comment by Lethany** [comment] 2021-11-28 22:52
@SavvaGrigoryan Alright, thanks for actually making an issue and bringing this up. This will be marked as closed for now.

**Closed** 2021-11-28 22:53 UTC
Labels: bug
